kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: ocm-placement-consumer
    namespace: argocd
rules:
    - apiGroups: ['cluster.open-cluster-management.io']
      resources: ['placementdecisions']
      verbs: ['get', 'list']