
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: ocm-placement-consumer:argocd
    namespace: argocd
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: ocm-placement-consumer
subjects:
    - kind: ServiceAccount
      namespace: argocd
      name: argocd-applicationset-controller

